service: aws-instagramdownloader
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    host: "0.0.0.0"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    TELEGRAM_TOKEN: ${env.TELEGRAM_TOKEN}
    USER_AGENT: ${env.USER_AGENT}
    X_IG_APP_ID: ${env.X_IG_APP_ID}
    INSTA_COOKIES: ${env.INSTA_COOKIES}

functions:
  webhook:
    handler: dist/app.webhook
    events:
     - http:
         path: webhook
         method: post
         cors: true
    timeout: 60