service: aws-instagramdownloader
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-esbuild

useDotenv: true

custom:
  esbuild:
    packager: npm
    packagePath: package.json
    packagerOptions: # optional - packager related options, currently supports only 'scripts' for both npm, pnpm and yarn
      scripts: # scripts to be executed, can be a string or array of strings
        - echo 'Hello World!'
        - rm -rf node_modules
    minify: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    TELEGRAM_TOKEN: ${env.TELEGRAM_TOKEN}
    USER_AGENT: ${env.USER_AGENT}
    X_IG_APP_ID: ${env.X_IG_APP_ID}
    INSTA_COOKIES: ${env.INSTA_COOKIES}

functions:
  webhook:
    handler: dist/app.webhook
    events:
     - http:
         path: webhook
         method: post
         cors: true